import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {snapshot,digest} from '../src/provenance.js';
import {readConfig} from '../src/files.js';
import {proposeBrowserMappings,proposeBrowserInstrumentation,inspectBrowserBuildArtifacts,validateBrowserBuildArtifacts} from '../src/browser-evidence.js';
import {browserMappingProof} from '../scripts/browser-mapping-proof.js';
const write=(root,file,text)=>{fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),text);};
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'browser-evidence-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));write(root,'public/landing.html','<h1>Landing</h1>');write(root,'public/app.js','window.ready=true;\n//# sourceMappingURL=app.js.map');write(root,'public/app.js.map',JSON.stringify({version:3,sources:['../src/app.js'],names:[],mappings:'AAAA'}));write(root,'src/app.js','window.ready=true;');write(root,'browser/landing.spec.js',"import {test,expect} from '@playwright/test';test('landing',async()=>{});");return root;}
function record(root,modify={}){const payload={schemaVersion:1,type:'browser',configurationHash:digest(readConfig(root)),provenance:snapshot(root,readConfig(root)),complete:true,warnings:[],observations:[{file:'browser/landing.spec.js',caseId:'case-1',nativeId:'native-1',repeatEachIndex:0,routes:['http://127.0.0.1:1234/landing.html'],requests:[{url:'http://127.0.0.1:1234/landing.html',type:'document',status:200},{url:'http://127.0.0.1:1234/app.js',type:'script',status:200}],coverage:{javascript:[],css:[]},complete:true}],...modify};return {...payload,integrity:digest(payload)};}
const authority={urlRoots:[{origin:'http://127.0.0.1:1234',urlPrefix:'/',directory:'public'}]};
test('explicit same-origin authority maps bundles and tracked local source maps as review-only proposals',t=>{const root=setup(t),before=fs.readFileSync(path.join(root,'browser/landing.spec.js'),'utf8'),proposal=proposeBrowserMappings(root,record(root),authority);assert.equal(proposal.reviewRequired,true);assert.equal(proposal.closedWorld,false);assert.deepEqual(proposal.caseMappings[0].dependencies,['browser/landing.spec.js','public/app.js','public/app.js.map','public/landing.html','src/app.js']);assert.equal(fs.existsSync(path.join(root,'tddswarm.config.json')),false);assert.equal(fs.readFileSync(path.join(root,'browser/landing.spec.js'),'utf8'),before);});
test('manual routes remain untouched and unresolved requests stay explicit',t=>{const root=setup(t);write(root,'tddswarm.config.json',JSON.stringify({browser:{routes:{'/landing.html':{tests:['browser/landing.spec.js'],inputs:['src/app.js']}}}}));const proposal=proposeBrowserMappings(root,record(root),{urlRoots:[]});assert.deepEqual(proposal.proposed.browser.routes,{});assert.ok(proposal.warnings.includes('manual-browser-route-preserved:/landing.html'));assert.equal(proposal.caseMappings[0].unresolved.length,2);});
test('stale source and altered sealed evidence are rejected',t=>{const root=setup(t),evidence=record(root);evidence.complete=false;assert.throws(()=>proposeBrowserMappings(root,evidence,authority),/integrity/);const current=record(root);write(root,'src/app.js','window.ready=false;');assert.throws(()=>proposeBrowserMappings(root,current,authority),/stale/);});
test('malformed, remote and symlink source maps cannot manufacture local edges',t=>{const root=setup(t);write(root,'public/app.js.map',JSON.stringify({version:3,sources:['https://remote.invalid/app.js']}));let proposal=proposeBrowserMappings(root,record(root),authority);assert.ok(proposal.warnings.includes('source-map-unresolved:public/app.js'));assert.ok(!proposal.caseMappings[0].dependencies.includes('src/app.js'));write(root,'public/app.js','window.ready=true;\n//# sourceMappingURL=https://remote.invalid/app.map');proposal=proposeBrowserMappings(root,record(root),authority);assert.ok(proposal.warnings.includes('source-map-reference-unsupported:public/app.js'));fs.unlinkSync(path.join(root,'public/app.js'));fs.symlinkSync(path.join(root,'src/app.js'),path.join(root,'public/app.js'));proposal=proposeBrowserMappings(root,record(root),authority);assert.ok(proposal.caseMappings[0].unresolved.some(request=>request.type==='script'));});
test('URL credentials/query strings and outside-project authority are rejected',t=>{const root=setup(t);assert.throws(()=>proposeBrowserMappings(root,record(root),{urlRoots:[{...authority.urlRoots[0],origin:'http://user:secret@localhost/'}]}),/redacted/);assert.throws(()=>proposeBrowserMappings(root,record(root),{urlRoots:[{...authority.urlRoots[0],directory:'../outside'}]}),/Unsafe/);});
test('incomplete capture remains incomplete and receives no closed-world authority',t=>{const root=setup(t),proposal=proposeBrowserMappings(root,record(root,{complete:false,warnings:['missing-browser-instrumentation']}),authority);assert.equal(proposal.observationsComplete,false);assert.equal(proposal.closedWorld,false);assert.ok(proposal.warnings.includes('missing-browser-instrumentation'));});
test('AST instrumentation preserves named aliases, expect and type imports without writing files',async t=>{const root=setup(t);const original="import { test as check, expect, type Page } from '@playwright/test';\ncheck('name',async({page}: {page:Page})=>{await expect(page).toBeTruthy();});\n";write(root,'browser/alias.spec.ts',original);const proposal=await proposeBrowserInstrumentation(root,{files:['browser/alias.spec.ts']});assert.equal(proposal.files.length,1);assert.equal(proposal.files[0].originalHash,digest(original));assert.match(proposal.files[0].content,/test as __testloreBaseTest, expect, type Page/);assert.match(proposal.files[0].content,/const check = __testloreCreateBrowserTest\(__testloreBaseTest\)/);assert.equal(fs.readFileSync(path.join(root,'browser/alias.spec.ts'),'utf8'),original);});
test('instrumentation rejects unknown fixtures, namespace imports and ambiguous SDK bindings',async t=>{const root=setup(t);write(root,'browser/custom.spec.js',"import {test} from './fixtures.js';test('x',()=>{});");write(root,'browser/ns.spec.js',"import * as sdk from '@playwright/test';sdk.test('x',()=>{});");write(root,'browser/duplicate.spec.js',"import {test as one,test as two} from '@playwright/test';");const proposal=await proposeBrowserInstrumentation(root,{files:['browser/custom.spec.js','browser/ns.spec.js','browser/duplicate.spec.js']});assert.equal(proposal.files.length,0);assert.equal(proposal.rejected.length,3);});
if(process.env.TESTLORE_PLAYWRIGHT_BROWSER==='1')test('real Chromium maps isolated HTML/style/bundle/source inputs and preserves three independent named faults',()=>{const result=browserMappingProof();assert.equal(result.passed,true,JSON.stringify(result));});

test('fixture remains inert without capture and records only redacted URLs when explicitly enabled',async t=>{
 const {createBrowserTest}=await import('../src/browser-fixture.js');let fixture;createBrowserTest({extend:definition=>{fixture=definition.page;return definition;}});
 const listeners={},contextListeners={},page={on:(event,listener)=>listeners[event]=listener,off:()=>{},mainFrame:()=>page,coverage:{startJSCoverage:async()=>{},startCSSCoverage:async()=>{},stopJSCoverage:async()=>[{url:'http://localhost/app.js?token=secret',functions:[{ranges:[{startOffset:0,endOffset:5,count:1}]}]}],stopCSSCoverage:async()=>[]}};
 const context={on:(event,listener)=>contextListeners[event]=listener,off:()=>{},browser:()=>({version:()=> 'fixture-only'})};
 const old=process.env.TESTLORE_BROWSER_CAPTURE_DIRECTORY;t.after(()=>{if(old===undefined)delete process.env.TESTLORE_BROWSER_CAPTURE_DIRECTORY;else process.env.TESTLORE_BROWSER_CAPTURE_DIRECTORY=old;});delete process.env.TESTLORE_BROWSER_CAPTURE_DIRECTORY;
 let used;await fixture({page,browserName:'chromium',context},async value=>used=value,{testId:'case',repeatEachIndex:0,retry:0});assert.equal(used,page);assert.equal(Object.keys(listeners).length,0);
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'browser-fixture-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));process.env.TESTLORE_BROWSER_CAPTURE_DIRECTORY=root;
 await fixture({page,browserName:'chromium',context},async()=>{listeners.framenavigated(Object.assign(page,{url:()=> 'http://name:secret@localhost/landing?token=private#fragment'}));listeners.response({url:()=> 'http://localhost/app.js?token=private',status:()=>200,request:()=>({resourceType:()=> 'script'})});},{testId:'case',repeatEachIndex:0,retry:0});
 const text=fs.readFileSync(path.join(root,fs.readdirSync(root)[0]),'utf8'),report=JSON.parse(text);assert.equal(report.complete,true);assert.deepEqual(report.routes,['http://localhost/landing']);assert.ok(!/secret|private|fragment/.test(text));assert.equal(report.coverage.javascript[0].ranges.length,1);
});

function generatedSetup(t){const root=setup(t);write(root,'dist/app.js','window.ready=true;\n//# sourceMappingURL=app.js.map');write(root,'dist/app.js.map',JSON.stringify({version:3,sources:['../src/app.js'],names:[],mappings:'AAAA'}));write(root,'.gitignore','dist/\nbuild/\n');execFileSync('git',['init','-q',root]);execFileSync('git',['-C',root,'add','.']);assert.equal(execFileSync('git',['-C',root,'check-ignore','dist/app.js'],{encoding:'utf8'}).trim(),'dist/app.js');return root;}
test('ignored generated bundles expose tracked source suggestions without routing completeness authority',t=>{const root=generatedSetup(t),manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});assert.equal(manifest.artifacts[0].generated,true);assert.deepEqual(manifest.artifacts[0].sources,[{path:'src/app.js',sha256:digest('window.ready=true;')}]);assert.equal(Object.hasOwn(manifest.provenance.files,'dist/app.js'),false);assert.equal(manifest.buildComplete,false);const evidence=record(root,{observations:[{file:'browser/landing.spec.js',caseId:'case-1',nativeId:'native-1',repeatEachIndex:0,routes:['http://127.0.0.1:1234/landing'],requests:[{url:'http://127.0.0.1:1234/app.js',type:'script',status:200}],coverage:{javascript:[],css:[]},complete:true}]});const proposal=proposeBrowserMappings(root,evidence,{urlRoots:[{origin:'http://127.0.0.1:1234',urlPrefix:'/',directory:'dist'}],buildManifest:manifest});assert.deepEqual(proposal.caseMappings[0].sourceSuggestions,['src/app.js']);assert.deepEqual(proposal.caseMappings[0].dependencies,['browser/landing.spec.js']);assert.ok(proposal.warnings.includes('unverified-build-completeness'));assert.equal(proposal.caseMappings[0].unresolved[0].reason,'generated-build-completeness-unverified');assert.equal(proposal.closedWorld,false);assert.equal(proposal.buildManifestHash,digest(manifest));});
test('generated artifact/map tampering and source/config drift invalidate sealed build inspection',t=>{const root=generatedSetup(t);let manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});write(root,'dist/app.js','window.ready=false;\n//# sourceMappingURL=app.js.map');assert.throws(()=>validateBrowserBuildArtifacts(root,manifest),/bytes or mapping references changed/);manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});write(root,'dist/app.js.map',JSON.stringify({version:3,sources:[],names:[],mappings:''}));assert.throws(()=>validateBrowserBuildArtifacts(root,manifest),/bytes or mapping references changed/);manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});write(root,'src/app.js','window.ready=false;');assert.throws(()=>validateBrowserBuildArtifacts(root,manifest),/stale/);manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});write(root,'tddswarm.config.json',JSON.stringify({adapter:'playwright'}));assert.throws(()=>validateBrowserBuildArtifacts(root,manifest),/stale/);});
test('inspection rejects escaped/symlink/internal paths, duplicate normalized artifacts and byte overflow',t=>{const root=generatedSetup(t);assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts:['../app.js']}),/Unsafe/);assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js','./dist/app.js']}),/Duplicate/);assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts:['node_modules/private.js']}),/unsupported/);fs.symlinkSync(path.join(root,'src/app.js'),path.join(root,'dist/linked.js'));assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts:['dist/linked.js']}),/Symlink/);write(root,'dist/oversized.js','x'.repeat(2*1024*1024+1));assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts:['dist/oversized.js']}),/size bound/);});
test('unknown build maps remain unresolved and inspection never executes configured service probes',t=>{const root=generatedSetup(t);write(root,'dist/app.js.map',JSON.stringify({version:3,sources:['../../outside.js'],names:[],mappings:''}));const manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});assert.deepEqual(manifest.artifacts[0].sources,[]);assert.ok(manifest.artifacts[0].warnings.includes('build-source-map-unresolved'));const evidence=record(root);write(root,'tddswarm.config.json',JSON.stringify({services:{api:{tests:['browser/landing.spec.js'],probe:[process.execPath,'-e',"require('node:fs').writeFileSync('executed.txt','bad')"]}}}));assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']}),/cannot execute service probes/);assert.throws(()=>proposeBrowserMappings(root,evidence,{...authority,buildManifest:manifest}),/cannot execute service probes/);assert.equal(fs.existsSync(path.join(root,'executed.txt')),false);});

test('build hashes bind raw bytes even when invalid UTF-8 decodes to the same replacement character',t=>{const root=generatedSetup(t);fs.writeFileSync(path.join(root,'dist/app.js'),Buffer.from([0xff]));const manifest=inspectBrowserBuildArtifacts(root,{artifacts:['dist/app.js']});fs.writeFileSync(path.join(root,'dist/app.js'),Buffer.from([0xfe]));assert.throws(()=>validateBrowserBuildArtifacts(root,manifest),/bytes or mapping references changed/);});
test('source reference budgets reject oversized manifest fan-out',t=>{const root=generatedSetup(t),artifacts=[];for(let index=0;index<6;index++){const file=`dist/chunk-${index}.js`;write(root,file,`window.ready=true;\n//# sourceMappingURL=chunk-${index}.js.map`);write(root,`dist/chunk-${index}.js.map`,JSON.stringify({version:3,sources:Array(2000).fill('../src/app.js'),names:[],mappings:''}));artifacts.push(file);}assert.throws(()=>inspectBrowserBuildArtifacts(root,{artifacts}),/source reference count exceeds bound/);});
