import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fixture,write} from './helpers.js';
import {git} from '../src/files.js';
import {planGeneration,localAqe,generationBindingFresh} from '../src/generation-routing.js';
const requirements='The public numeric parser must preserve finite numbers and reject blank inputs.';
function setup(t){const root=fixture(t,{'src/index.js':'export const parse=x=>x;','worker.mjs':'process.stdout.write("{}");'});write(root,'node_modules/agentic-qe/package.json',{name:'agentic-qe',version:'3.14.8',bin:{aqe:'./dist/cli.cjs'}});write(root,'node_modules/agentic-qe/dist/cli.cjs','console.log("fixture only");');return root;}
const options={config:{adapter:'vitest'},agent:[process.execPath,'worker.mjs'],requirements,tasks:[{subject:'src/index.js'}]};
test('automatic planning binds a compatible local author without probing, installing or changing configuration',t=>{const root=setup(t),before=fs.readdirSync(root),plan=planGeneration(root,options);assert.equal(plan.provider,'agentic-qe');assert.equal(plan.mode,'auto');assert.equal(plan.maxParallelAuthors,2);assert.equal(plan.plugin.framework,'vitest');assert.equal(plan.ready,true);assert.deepEqual(plan.cost,{tokens:null,currency:null});assert.match(plan.limitations.join(' '),/no AQE advantage is proven/);assert.deepEqual(fs.readdirSync(root),before);assert.equal(generationBindingFresh(root,plan),true);write(root,'node_modules/agentic-qe/dist/cli.cjs','changed');assert.equal(generationBindingFresh(root,plan),false);});
test('Node, repair, explicit disabled/custom worker and JSON selections retain their author',t=>{const root=setup(t);for(const override of [{config:{adapter:'node'}},{kind:'source-repair'},{config:{adapter:'vitest',plugins:{'agentic-qe':{enabled:false}}}},{config:{adapter:'vitest',plugins:{custom:{enabled:true,kind:'worker'}}}},{provider:'json-worker'}]){const plan=planGeneration(root,{...options,...override});assert.equal(plan.provider,'json-worker');assert.ok(plan.reasons.length);}assert.equal(planGeneration(root,{...options,config:{adapter:'jest'}}).provider,'agentic-qe');});
test('auto requires meaningful requirements, available worker and distinct existing production tasks',t=>{const root=setup(t);for(const override of [{requirements:''},{requirements:'TODO write meaningful behavior expectations'},{agent:['nonexistent-qe-worker']},{agent:[process.execPath,'missing.mjs']},{tasks:[]},{tasks:[{subject:'../escape.js'}]},{tasks:[{subject:'test/index.test.js'}]},{tasks:[{subject:'src/index.js'},{subject:'src/index.js'}]}])assert.equal(planGeneration(root,{...options,...override}).provider,'json-worker');});
test('unavailable versions, escaping bins, package symlinks and substituted aliases fail closed',t=>{const root=setup(t);for(const pkg of [{name:'agentic-qe',version:'3.14.9',bin:'dist/cli.cjs'},{name:'different',version:'3.14.8',bin:'dist/cli.cjs'},{name:'agentic-qe',version:'3.14.8',bin:'../../worker.mjs'}]){write(root,'node_modules/agentic-qe/package.json',pkg);assert.equal(localAqe(root),null);}write(root,'node_modules/agentic-qe/package.json',{name:'agentic-qe',version:'3.14.8',bin:'dist/cli.cjs'});fs.mkdirSync(path.join(root,'node_modules/.bin'),{recursive:true});fs.symlinkSync(path.join(root,'worker.mjs'),path.join(root,'node_modules/.bin/aqe'));assert.equal(localAqe(root),null);fs.unlinkSync(path.join(root,'node_modules/.bin/aqe'));fs.unlinkSync(path.join(root,'node_modules/agentic-qe/package.json'));fs.symlinkSync(path.join(root,'worker.mjs'),path.join(root,'node_modules/agentic-qe/package.json'));assert.equal(localAqe(root),null);});
test('explicit AQE preserves manual command/framework but never bypasses enablement',t=>{const root=setup(t),setting={enabled:true,command:['custom-aqe'],framework:'node'};const plan=planGeneration(root,{config:{plugins:{'agentic-qe':setting}}});assert.equal(plan.mode,'explicit');assert.equal(plan.provider,'agentic-qe');assert.deepEqual(plan.plugin,setting);assert.throws(()=>planGeneration(root,{...options,provider:'agentic-qe'}),/Enable/);assert.throws(()=>planGeneration(root,{...options,provider:'competing'}),/Unsupported/);});

test('improvement-style shared installation requires explicit parent provenance and exact root, revision and alias binding',t=>{
 const original=setup(t);write(original,'.gitignore','node_modules/\n');git(original,['init']);git(original,['config','user.email','fixture@example.invalid']);git(original,['config','user.name','fixture']);git(original,['add','.']);git(original,['commit','-m','fixture']);
 const sourceHead=git(original,['rev-parse','HEAD']).trim(),root=fixture(t);git(root,['init']);git(root,['remote','add','origin',original]);git(root,['fetch','origin','HEAD']);git(root,['reset','--hard','FETCH_HEAD']);
 fs.symlinkSync(fs.realpathSync(path.join(original,'node_modules')),path.join(root,'node_modules'),'dir');
 assert.equal(localAqe(root),null);
 const dependencyMetadata={root:fs.realpathSync(original),nodeModules:fs.realpathSync(path.join(original,'node_modules')),sourceHead};
 const plan=planGeneration(root,{...options,dependencyMetadata});assert.equal(plan.provider,'agentic-qe');assert.equal(generationBindingFresh(root,plan,{dependencyMetadata}),true);
 assert.equal(localAqe(root,{dependencyMetadata:{...dependencyMetadata,sourceHead:'0'.repeat(40)}}),null);
 assert.equal(localAqe(root,{dependencyMetadata:{...dependencyMetadata,nodeModules:path.join(root,'node_modules')}}),null);
 write(original,'node_modules/agentic-qe/dist/cli.cjs','changed');assert.equal(generationBindingFresh(root,plan,{dependencyMetadata}),false);
});
