import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {fixture,commit,twoModules} from './helpers.js';import {freezePublicCandidates,preparePublicCandidate,executePreparedPublic} from '../scripts/public-corpus.js';import {preflightPublicCandidate} from '../scripts/public-corpus-preflight.js';
const git=(root,...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();
test('independent preflight preserves originals and rejects an unchanged failing baseline without routing claims',t=>{
 const source=fixture(t,twoModules);fs.writeFileSync(path.join(source,'src/a.js'),'export const a = 9;');commit(source);const parent=git(source,'rev-parse','HEAD');fs.writeFileSync(path.join(source,'src/a.js'),'export const a = 1;');commit(source);const head=git(source,'rev-parse','HEAD');git(source,'remote','add','origin','https://github.com/example/repo');
 const candidate={id:'genuine-controller-fixture',repository:'https://github.com/example/repo',fixRevision:head,parentRevision:parent,treeRevision:git(source,'rev-parse','HEAD^{tree}'),changedFiles:[{path:'src/a.js',headGitBlob:git(source,'rev-parse','HEAD:src/a.js'),patchSha256:'a'.repeat(64)},{path:'test/a.test.js',headGitBlob:git(source,'rev-parse','HEAD:test/a.test.js'),patchSha256:'b'.repeat(64)}],sourcePaths:['src/a.js'],maintainerOraclePaths:['test/a.test.js'],kind:'public-bugfix-inversion-candidate',status:'unmeasured',blockers:[]};
 const selection=freezePublicCandidates({candidates:[candidate],accounting:[]}),profile={reviewed:true,candidateId:candidate.id,root:source,scope:'Constructed controller fixture; no independent public bug claim',config:{adapter:'node',discovery:'native'}};const out=fixture(t,{}),result=preflightPublicCandidate(selection,candidate.id,profile,path.join(out,'preflight'));assert.equal(result.completed,true,JSON.stringify(result));assert.equal(result.qualified,false);assert.match(result.implementationIdentity.sourceRevision,/^[a-f0-9]{40}$/);assert.ok(result.implementationIdentity.implementationHashes['src/execution.js']);assert.equal(result.independentFullFaultRuns,2);assert.deepEqual(result.expectedFailureNames,['a']);assert.equal(git(source,'status','--porcelain'),'');assert.equal(fs.readFileSync(path.join(source,'src/a.js'),'utf8'),'export const a = 1;');assert.throws(()=>preflightPublicCandidate(selection,candidate.id,profile,path.join(out,'preflight')),/exist/i);
 fs.writeFileSync(path.join(source,'src/b.js'),'export const b = 9;');commit(source);const changedHead=git(source,'rev-parse','HEAD'),nextCandidate={...candidate,fixRevision:changedHead,parentRevision:head,treeRevision:git(source,'rev-parse','HEAD^{tree}'),sourcePaths:['src/b.js'],changedFiles:[{path:'src/b.js',headGitBlob:git(source,'rev-parse','HEAD:src/b.js'),patchSha256:'c'.repeat(64)},{path:'test/a.test.js',headGitBlob:git(source,'rev-parse','HEAD:test/a.test.js'),patchSha256:'d'.repeat(64)}]};const bad=preflightPublicCandidate(freezePublicCandidates({candidates:[nextCandidate],accounting:[]}),candidate.id,profile,path.join(out,'bad'));assert.equal(bad.completed,false);assert.match(bad.error,/baseline must pass/);assert.ok(fs.existsSync(path.join(out,'bad/baseline.json')));assert.equal(fs.existsSync(path.join(out,'bad/fault-0.json')),false);
});
test('frozen cache policy reaches independent native executions and all pilot arms without ambient credential forwarding',t=>{
 const marker=twoModules['test/a.test.js']+'\ntest("cache-control marker",()=>{assert.equal(process.env.JITI_FS_CACHE,"false");assert.equal(process.env.TESTLORE_POLICY_SECRET,undefined);});\n';
 const source=fixture(t,{...twoModules,'test/a.test.js':marker});fs.writeFileSync(path.join(source,'src/a.js'),'export const a = 9;');commit(source);const parent=git(source,'rev-parse','HEAD');fs.writeFileSync(path.join(source,'src/a.js'),'export const a = 1;');commit(source);const head=git(source,'rev-parse','HEAD');git(source,'remote','add','origin','https://github.com/example/cache-policy');
 const id='cache-policy-controller',candidate={id,repository:'https://github.com/example/cache-policy',fixRevision:head,parentRevision:parent,treeRevision:git(source,'rev-parse','HEAD^{tree}'),changedFiles:[{path:'src/a.js',headGitBlob:git(source,'rev-parse','HEAD:src/a.js'),patchSha256:'a'.repeat(64)},{path:'test/a.test.js',headGitBlob:git(source,'rev-parse','HEAD:test/a.test.js'),patchSha256:'b'.repeat(64)}],sourcePaths:['src/a.js'],maintainerOraclePaths:['test/a.test.js'],kind:'public-bugfix-inversion-candidate',status:'unmeasured',blockers:[]},selection=freezePublicCandidates({candidates:[candidate],accounting:[]}),profile={reviewed:true,candidateId:id,root:source,scope:'Constructed explicit-cache and credential-isolation marker; no public defect claim',config:{adapter:'node',discovery:'native'},cachePolicy:{jitiFilesystem:false}},output=fixture(t,{}),originalCache=process.env.JITI_FS_CACHE,originalSecret=process.env.TESTLORE_POLICY_SECRET;
 process.env.JITI_FS_CACHE='true';process.env.TESTLORE_POLICY_SECRET='synthetic-private-canary';
 try{const pre=preflightPublicCandidate(selection,id,profile,path.join(output,'positive'));assert.equal(pre.completed,true,JSON.stringify(pre));assert.deepEqual(pre.cachePolicy,{jitiFilesystem:false});assert.equal(process.env.JITI_FS_CACHE,'true');assert.equal(process.env.TESTLORE_POLICY_SECRET,'synthetic-private-canary');
  const prepared=preparePublicCandidate(selection,id,{...profile,expectedFailureNames:pre.expectedFailureNames,baselineDeclaredSkips:pre.baselineDeclaredSkips});assert.deepEqual(prepared.corpus.pilot.cachePolicy,{jitiFilesystem:false});const changed=structuredClone(prepared);delete changed.corpus.pilot.cachePolicy;assert.throws(()=>executePreparedPublic(output,selection,changed,'.tddswarm/pilots/drift'),/commitment/);const run=executePreparedPublic(output,selection,prepared,'.tddswarm/pilots/cache-policy');assert.equal(run.assessment.qualified,true,JSON.stringify(run));for(let i=0;i<2;i++)for(const arm of['full','subset','native']){const result=JSON.parse(fs.readFileSync(path.join(output,'.tddswarm/pilots/cache-policy/pilot',prepared.corpus.pilot.projects[0].name,'change-0-trial-'+i+'-'+arm+'.json')));assert.ok(result.tests.some(c=>c.name==='cache-control marker'&&c.status==='passed'));}assert.equal(git(source,'status','--porcelain'),'');
  // The absent policy is a real negative control: ambient JITI is stripped,
  // so the marker fails instead of a flag being silently treated as declared.
  const noPolicy={...profile};delete noPolicy.cachePolicy;const rejected=preflightPublicCandidate(selection,id,noPolicy,path.join(output,'negative'));assert.equal(rejected.completed,false);assert.match(rejected.error,/baseline must pass/);assert.equal(fs.existsSync(path.join(output,'negative/fault-0.json')),false);
 }finally{if(originalCache===undefined)delete process.env.JITI_FS_CACHE;else process.env.JITI_FS_CACHE=originalCache;if(originalSecret===undefined)delete process.env.TESTLORE_POLICY_SECRET;else process.env.TESTLORE_POLICY_SECRET=originalSecret;}
});
