import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';
import {fileIdentity} from '../scripts/worker-identity.js';
import {fixture,commit,twoModules} from './helpers.js';import {digest} from '../src/provenance.js';import {freezePublicCandidates,preparePublicCandidate,executePreparedPublic,publicAttemptSummary} from '../scripts/public-corpus.js';import {upstreamInputs,installedTreeIdentity,boundedInstallProcess,verifyUpstreamInstallation,publicVerificationDiagnostic,privateVerificationDiagnostic,validateInstalledInventory,installedInventoryDifference} from '../scripts/public-corpus-upstream.js';
const git=(root,...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();
function fixed(t){const root=fixture(t,{...twoModules,'.gitignore':'node_modules/\n.tddswarm/\n','package.json':'{"type":"module","packageManager":"pnpm@8.9.2"}','pnpm-lock.yaml':'lockfileVersion: 6.0\n'});fs.writeFileSync(path.join(root,'src/a.js'),'export const a=9;');commit(root);const parent=git(root,'rev-parse','HEAD');fs.writeFileSync(path.join(root,'src/a.js'),'export const a=1;');commit(root);const head=git(root,'rev-parse','HEAD');git(root,'remote','add','origin','https://github.com/example/upstream');const selection=freezePublicCandidates({candidates:[{id:'upstream-example',repository:'https://github.com/example/upstream',fixRevision:head,parentRevision:parent,treeRevision:git(root,'rev-parse','HEAD^{tree}'),changedFiles:[{path:'src/a.js',headGitBlob:git(root,'rev-parse','HEAD:src/a.js'),patchSha256:'a'.repeat(64)}],sourcePaths:['src/a.js'],maintainerOraclePaths:[],kind:'public-bugfix-inversion-candidate',status:'unmeasured',blockers:[],runtimeIdentity:{packageManager:'pnpm@8.9.2'},byteBindings:['package.json','pnpm-lock.yaml'].map(file=>({kind:'dependency',path:file,gitBlob:git(root,'rev-parse','HEAD:'+file),bytes:fs.statSync(path.join(root,file)).size,sha256:digest(fs.readFileSync(path.join(root,file)))}))}],accounting:[]});return{root,selection,id:'upstream-example'};}
test('upstream install binds exact commit, parent, manager and frozen manifest/lock before network execution',t=>{const f=fixed(t);assert.equal(upstreamInputs(f.selection,f.id,f.root).packageManager,'pnpm@8.9.2');fs.writeFileSync(path.join(f.root,'pnpm-lock.yaml'),'changed');assert.throws(()=>upstreamInputs(f.selection,f.id,f.root),/clean exact/);});
test('installed fingerprint detects content/link drift and rejects outside links and hardlink aliases',t=>{const root=fixture(t,{}),modules=path.join(root,'node_modules');fs.mkdirSync(path.join(modules,'package'),{recursive:true});fs.writeFileSync(path.join(modules,'package/a.js'),'original');fs.symlinkSync('package',path.join(modules,'alias'));fs.symlinkSync(modules,path.join(root,'borrowed-modules'));assert.throws(()=>installedTreeIdentity(path.join(root,'borrowed-modules')),/real project-local/);const before=installedTreeIdentity(modules);assert.throws(()=>installedTreeIdentity(modules,{maxMs:-1}),/hashing deadline/);fs.writeFileSync(path.join(modules,'package/a.js'),'changed');assert.notEqual(installedTreeIdentity(modules).sha256,before.sha256);fs.symlinkSync(os.tmpdir(),path.join(modules,'escape'));assert.throws(()=>installedTreeIdentity(modules),/escapes/);fs.unlinkSync(path.join(modules,'escape'));fs.linkSync(path.join(modules,'package/a.js'),path.join(root,'outside'));assert.throws(()=>installedTreeIdentity(modules),/hardlink/);});
test('verification diagnostics distinguish content drift from inventory rejection without exposing paths',t=>{
 const f=fixed(t),modules=path.join(f.root,'node_modules');fs.mkdirSync(modules);const leaf=path.join(modules,'x.js');fs.writeFileSync(leaf,'one');
 const receipt={...upstreamInputs(f.selection,f.id,f.root),status:'completed',upstreamLockInstallationVerified:true,kind:'upstream-frozen-installation',project:fs.realpathSync(f.root),install:{exitCode:0,reason:null},installedTree:installedTreeIdentity(modules)},file=path.join(f.root,'.tddswarm/diagnostic.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(receipt));const hash=digest(fs.readFileSync(file));
 const rejected=expectedHash=>{let error;try{verifyUpstreamInstallation(f.selection,f.id,f.root,file,expectedHash);}catch(caught){error=caught;}assert.ok(error);const diagnostic=publicVerificationDiagnostic(error,receipt.installedTree);assert.equal(JSON.stringify(diagnostic).includes(f.root),false);return diagnostic;};
 assert.equal(rejected('0'.repeat(64)).stage,'receipt-binding-failed');fs.writeFileSync(leaf,'two');const drift=rejected(hash);assert.equal(drift.stage,'digest-mismatch');assert.notEqual(drift.expected.sha256,drift.observed.sha256);assert.equal(drift.observed.files,1);
 fs.linkSync(leaf,path.join(f.root,'.tddswarm','outside-alias'));const inventory=rejected(hash);assert.equal(inventory.stage,'inventory-failed');assert.equal(inventory.observed,null);
 const opaque=publicVerificationDiagnostic({message:'private/path/token',verificationDiagnostic:{stage:'private/path/token',observed:{sha256:'private/path/token'}}},{...receipt.installedTree,extra:'private/path/token'});assert.equal(opaque.stage,'verification-exception');assert.equal(opaque.observed,null);assert.equal(JSON.stringify(opaque).includes('private/path/token'),false);
});
test('bound upstream receipt fails closed on substitution and post-install byte drift',t=>{const f=fixed(t),modules=path.join(f.root,'node_modules');fs.mkdirSync(modules);fs.writeFileSync(path.join(modules,'x.js'),'one');const input=upstreamInputs(f.selection,f.id,f.root),receipt={...input,status:'completed',upstreamLockInstallationVerified:true,kind:'upstream-frozen-installation',project:fs.realpathSync(f.root),install:{exitCode:0,reason:null},installedTree:installedTreeIdentity(modules)},file=path.join(f.root,'.tddswarm/upstream-receipt.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(receipt));const hash=digest(fs.readFileSync(file));assert.equal(verifyUpstreamInstallation(f.selection,f.id,f.root,file,hash).status,'completed');assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,file,'0'.repeat(64)),/receipt binding/);fs.writeFileSync(path.join(modules,'x.js'),'two');assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,file,hash),/bytes changed/);});
test('installer retains timeout evidence and rejects unavailable disk reserve before spawning',async t=>{const root=fixture(t,{}),timed=path.join(root,'.tddswarm/timed');fs.mkdirSync(timed,{recursive:true});const result=await boundedInstallProcess(process.execPath,['-e','console.log("started");setInterval(()=>{},1000)'],{cwd:root,directory:timed,timeoutMs:200,reserveBytes:0});assert.equal(result.reason,'timeout');assert.match(fs.readFileSync(path.join(timed,'stdout.log'),'utf8'),/started/);const blocked=path.join(root,'.tddswarm/blocked');fs.mkdirSync(blocked);await assert.rejects(()=>boundedInstallProcess(process.execPath,['-e','process.exit(0)'],{cwd:root,directory:blocked,reserveBytes:Number.MAX_SAFE_INTEGER}),/reserve unavailable/);assert.equal(fs.readdirSync(blocked).length,0);});
test('upstream controller rejects unbounded install budgets before validating inputs or invoking package managers',async()=>{const {installUpstreamCandidate}=await import('../scripts/public-corpus-upstream.js');for(const budget of [{timeoutMs:180001},{reserveBytes:0},{maxGrowthBytes:451*1024**2}])await assert.rejects(()=>installUpstreamCandidate({...budget}),/bounded install deadline/);});
test('extended installation growth is restricted to exact reviewed defu source, manager and original lock bindings',async t=>{
 const {installUpstreamCandidate,upstreamInstallGrowthBudget,assertInstallGrowthBinding}=await import('../scripts/public-corpus-upstream.js');assert.equal(upstreamInstallGrowthBudget().maxGrowthBytes,450*1024**2);assert.deepEqual(upstreamInstallGrowthBudget('defu-original-lock-768mib'),{maxGrowthBytes:768*1024**2,minReserveBytes:2*1024**3});assert.throws(()=>upstreamInstallGrowthBudget('unbounded'),/Unknown/);
 const input={candidateId:'unjs-defu-11ba02213d4b',repository:'https://github.com/unjs/defu',fixRevision:'11ba02213d4b1c6b02dd686041f75edc479c98e9',parentRevision:'3942bfbbcaa72084bd4284846c83bd61ed7c8b29',packageManager:'pnpm@10.33.0',inputs:[{logicalPath:'package.json',sha256:'0ee5010fb716a695cb591b6b33d0a7287117f47344fcd8ae1b9dfe7f623054d2'},{logicalPath:'pnpm-lock.yaml',sha256:'8e25a8381354e1002b339db2196f23c243aebe2c91afc11219528fba6df07a36'}]};assert.doesNotThrow(()=>assertInstallGrowthBinding(input,'defu-original-lock-768mib'));
 for(const change of [{candidateId:'another'},{fixRevision:'a'.repeat(40)},{parentRevision:'b'.repeat(40)},{repository:'https://github.com/example/project'},{packageManager:'pnpm@10.33.1'},{inputs:input.inputs.map(x=>({...x,sha256:'0'.repeat(64)}))}])assert.throws(()=>assertInstallGrowthBinding({...input,...change},'defu-original-lock-768mib'),/reviewed original defu/);
 for(const budget of [{maxGrowthBytes:769*1024**2,reserveBytes:2*1024**3},{maxGrowthBytes:768*1024**2,reserveBytes:1024**3}])await assert.rejects(()=>installUpstreamCandidate({growthPolicy:'defu-original-lock-768mib',...budget}),/bounded install deadline/);
 const f=fixed(t),directory=path.join(f.root,'.tddswarm/never-install');await assert.rejects(()=>installUpstreamCandidate({...f,checkout:f.root,directory,growthPolicy:'defu-original-lock-768mib',maxGrowthBytes:768*1024**2,reserveBytes:2*1024**3}),/reviewed original defu/);assert.equal(fs.existsSync(directory),false);
});
test('fast zero-exit native commands cannot bypass final log limits; empty and normal logs retain hashes',async t=>{const root=fixture(t,{});for(const [name,text,budget,expected]of[['overflow','1234567890123456',8,'log-budget'],['normal','1234',8,null],['empty','',8,null]]){const directory=path.join(root,'.tddswarm/'+name);fs.mkdirSync(directory,{recursive:true});const result=await boundedInstallProcess('/bin/sh',['-c','printf "%s" "$1"','testlore',text],{cwd:root,directory,reserveBytes:0,maxLogBytes:budget});assert.equal(result.exitCode,0);assert.equal(result.reason,expected);assert.equal(fs.readFileSync(path.join(directory,'stdout.log'),'utf8'),text);assert.equal(result.finalResources.stdoutBytes,text.length);if(expected){assert.equal(result.stdoutSha256,null);assert.equal(result.stderrSha256,null);}else{assert.equal(result.stdoutSha256,digest(text));assert.equal(result.stderrSha256,digest(''));}}});
test('final native observation rejects completed late commands and reserve/growth breaches before the interval',async t=>{const root=fixture(t,{}),original=fs.statfsSync;for(const [name,initial,final,reserve,growth]of[['reserve',1000,10,100,2000],['growth',1000,800,0,100]]){let reads=0;fs.statfsSync=()=>({bavail:reads++===0?initial:final,bsize:1});const directory=path.join(root,'.tddswarm/'+name);fs.mkdirSync(directory,{recursive:true});try{const r=await boundedInstallProcess('/bin/sh',['-c','exit 0'],{cwd:root,directory,reserveBytes:reserve,maxGrowthBytes:growth});assert.equal(r.exitCode,0);assert.equal(r.reason,'disk-'+name);assert.equal(r.finalResources.availableBytes,final);}finally{fs.statfsSync=original;}}const directory=path.join(root,'.tddswarm/late');fs.mkdirSync(directory);const interval=globalThis.setInterval;t.mock.method(globalThis,'setInterval',(_callback,milliseconds)=>interval(()=>{},milliseconds));try{const late=await boundedInstallProcess('/bin/sh',['-c','sleep 0.02'],{cwd:root,directory,reserveBytes:0,timeoutMs:1});assert.equal(late.exitCode,0);assert.equal(late.reason,'timeout');}finally{t.mock.restoreAll();}});
test('isolated user/global configuration paths let the real pinned npm CLI initialize without network or installation',async t=>{const {isolatedManagerEnvironment}=await import('../scripts/public-corpus-upstream.js'),root=fixture(t,{}),directory=path.join(root,'.tddswarm/npm-config');fs.mkdirSync(directory,{recursive:true});const {env,configurationIsolation}=isolatedManagerEnvironment(directory,path.join(directory,'cache'));assert.notEqual(env.npm_config_userconfig,env.npm_config_globalconfig);assert.equal(configurationIsolation.length,2);assert.ok(configurationIsolation.every(i=>i.bytes===0));const npm=path.join(path.dirname(process.execPath),'..','lib','node_modules','npm','bin','npm-cli.js'),output=path.join(directory,'version');fs.mkdirSync(output);const result=await boundedInstallProcess(process.execPath,[npm,'--version'],{cwd:root,directory:output,reserveBytes:0,env});assert.equal(result.exitCode,0,fs.readFileSync(path.join(output,'stderr.log'),'utf8'));assert.equal(result.reason,null);assert.match(fs.readFileSync(path.join(output,'stdout.log'),'utf8'),/^\d+\.\d+\.\d+\s*$/);});
test('esbuild-style internal binary aliases are fully inventoried; late external aliases or removals reject hashing',t=>{for(const change of['outside','remove']){const root=fixture(t,{}),modules=path.join(root,'node_modules'),a=path.join(modules,'optional-platform/bin/esbuild'),b=path.join(modules,'esbuild/bin/esbuild');fs.mkdirSync(path.dirname(a),{recursive:true});fs.mkdirSync(path.dirname(b),{recursive:true});fs.writeFileSync(a,'native-binary');fs.linkSync(a,b);const before=installedTreeIdentity(modules);assert.deepEqual(before.internalHardlinkGroups,[['esbuild/bin/esbuild','optional-platform/bin/esbuild']]);assert.equal(before.files,2);const original=fs.readSync;let changed=false;fs.readSync=function(...args){const result=original.apply(this,args);if(!changed){changed=true;if(change==='outside')fs.linkSync(a,path.join(root,'outside-binary'));else fs.unlinkSync(b);}return result;};try{assert.throws(()=>installedTreeIdentity(modules),/changed during hashing|outside-tree alias|changed membership/);}finally{fs.readSync=original;}assert.equal(changed,true);}});
test('changing internal alias membership invalidates an otherwise unchanged upstream receipt',t=>{const f=fixed(t),modules=path.join(f.root,'node_modules');fs.mkdirSync(modules);fs.writeFileSync(path.join(modules,'a.bin'),'binary');fs.linkSync(path.join(modules,'a.bin'),path.join(modules,'b.bin'));const receipt={...upstreamInputs(f.selection,f.id,f.root),status:'completed',upstreamLockInstallationVerified:true,kind:'upstream-frozen-installation',project:fs.realpathSync(f.root),install:{exitCode:0,reason:null},installedTree:installedTreeIdentity(modules)},file=path.join(f.root,'.tddswarm/aliases.json');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(receipt));const hash=digest(fs.readFileSync(file));assert.equal(verifyUpstreamInstallation(f.selection,f.id,f.root,file,hash).status,'completed');fs.renameSync(path.join(modules,'b.bin'),path.join(modules,'c.bin'));assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,file,hash),/bytes changed/);});

test('missing historical source blob rejects admission before cloning or manager execution',t=>{const f=fixed(t),candidate=f.selection.candidates[0],blob=git(f.root,'rev-parse',candidate.parentRevision+':src/a.js');fs.unlinkSync(path.join(f.root,'.git/objects',blob.slice(0,2),blob.slice(2)));assert.throws(()=>upstreamInputs(f.selection,f.id,f.root),/locally available exact candidate/);});

function inventoryReceipt(f){
 const modules=path.join(f.root,'node_modules');fs.mkdirSync(modules);fs.writeFileSync(path.join(modules,'seed.bin'),'original');
 const {inventory,inventoryStatus,...tree}=installedTreeIdentity(modules,{captureInventory:true}),directory=path.join(f.root,'.tddswarm/inventory');fs.mkdirSync(directory,{recursive:true});
 const inventoryFile=path.join(directory,'installed-inventory.json');fs.writeFileSync(inventoryFile,JSON.stringify(inventory));
 const manager=path.join(directory,'manager.cjs'),metadata=path.join(directory,'manager.json');fs.writeFileSync(manager,'// fixture manager');fs.writeFileSync(metadata,'{}');
 const receipt={...upstreamInputs(f.selection,f.id,f.root),status:'completed',upstreamLockInstallationVerified:true,kind:'upstream-frozen-installation',project:fs.realpathSync(f.root),install:{exitCode:0,reason:null},manager:fileIdentity(manager),managerMetadata:fileIdentity(metadata),installedTree:tree,installedInventory:{status:'complete',filename:'installed-inventory.json',sha256:digest(fs.readFileSync(inventoryFile)),bytes:fs.statSync(inventoryFile).size}};
 const file=path.join(directory,'receipt.json'),save=()=>{fs.writeFileSync(file,JSON.stringify(receipt));return digest(fs.readFileSync(file));};return {modules,inventory,tree,receipt,file,inventoryFile,save};
}
test('separate installed inventory preserves the authoritative digest and bounds optional details',t=>{
 const modules=path.join(fixture(t,{}),'node_modules');fs.mkdirSync(modules);fs.writeFileSync(path.join(modules,'first'),'one');fs.writeFileSync(path.join(modules,'removed'),'two');
 const a=installedTreeIdentity(modules,{captureInventory:true}),{inventory,inventoryStatus,...summary}=a;assert.deepEqual(summary,installedTreeIdentity(modules));assert.equal(validateInstalledInventory(inventory,summary,modules),inventory);
 const forged=structuredClone(inventory);forged.entries[0][4]='0'.repeat(64);assert.throws(()=>validateInstalledInventory(forged,summary,modules),/digest/);
 for(const name of ['../escape','/absolute','a\\b']){const unsafe=structuredClone(inventory);unsafe.entries[0][0]=name;assert.throws(()=>validateInstalledInventory(unsafe,summary,modules),/path/);}
 const extra={...inventory,contents:'must never be admitted'};assert.throws(()=>validateInstalledInventory(extra,summary,modules),/bounded/);
 const overflow=installedTreeIdentity(modules,{captureInventory:true,maxInventoryBytes:1});assert.equal(overflow.inventory,null);assert.deepEqual(overflow.inventoryStatus,{status:'unavailable',reason:'byte-budget'});assert.equal(overflow.sha256,summary.sha256);
 assert.throws(()=>installedTreeIdentity(modules,{maxInventoryBytes:16*1024**2+1}),/bounded/);assert.throws(()=>installedTreeIdentity(modules,{maxFiles:1}),/file budget/);
 fs.writeFileSync(path.join(modules,'first'),'changed');fs.unlinkSync(path.join(modules,'removed'));fs.writeFileSync(path.join(modules,'new-a'),'abcdefghijklmnopqrstuvw');fs.writeFileSync(path.join(modules,'new-b'),'abcdefghijklmnopqrstuvw');
 const b=installedTreeIdentity(modules,{captureInventory:true}),diff=installedInventoryDifference(inventory,b.inventory,{root:modules});assert.equal(diff.addedCount,2);assert.equal(diff.removedCount,1);assert.equal(diff.changedCount,1);assert.deepEqual(diff.added.map(x=>x.path),['new-a','new-b']);assert.equal(diff.added[0].observed.bytes,23);assert.equal(diff.changed[0].expected.sha256,digest('one'));assert.equal(diff.changed[0].observed.sha256,digest('changed'));
 for(const limits of [{maxDetails:0},{maxDetails:1},{maxDiagnosticBytes:128}]){const short=installedInventoryDifference(inventory,b.inventory,{root:modules,...limits});assert.equal(short.status,'truncated');assert.equal(short.addedCount,2);assert.equal(short.removedCount,1);assert.equal(short.changedCount,1);assert.ok(short.detailCount<4);}
 const error={verificationDiagnostic:{stage:'digest-mismatch',expected:summary,observed:b,changes:diff}};const safe=publicVerificationDiagnostic(error,summary);assert.equal(JSON.stringify(safe).includes('new-a'),false);assert.equal(JSON.stringify(safe).includes(modules),false);assert.deepEqual(privateVerificationDiagnostic(error).changes.added,diff.added);
 error.verificationDiagnostic.changes.added[0].path='/private/path';assert.equal(privateVerificationDiagnostic(error).changes.status,'unavailable');
});
test('inventory records link and hardlink identities without admitting escaping links or changed membership',t=>{
 const modules=path.join(fixture(t,{}),'node_modules');fs.mkdirSync(modules);fs.writeFileSync(path.join(modules,'a'),'binary');fs.linkSync(path.join(modules,'a'),path.join(modules,'b'));fs.symlinkSync('a',path.join(modules,'link'));
 const a=installedTreeIdentity(modules,{captureInventory:true});assert.equal(validateInstalledInventory(a.inventory,a,modules),a.inventory);const forged=structuredClone(a.inventory);forged.entries.find(x=>x[1]==='link')[2]='../../escape';assert.throws(()=>validateInstalledInventory(forged,a,modules),/escapes/);
 fs.renameSync(path.join(modules,'b'),path.join(modules,'c'));const b=installedTreeIdentity(modules,{captureInventory:true}),diff=installedInventoryDifference(a.inventory,b.inventory,{root:modules});assert.equal(diff.linkMembershipChanged,true);assert.equal(diff.addedCount,1);assert.equal(diff.removedCount,1);assert.notEqual(a.sha256,b.sha256);
});
test('inventory byte bindings reject forged receipts while real added files retain precise bounded diagnostics',t=>{
 const f=fixed(t),r=inventoryReceipt(f);let hash=r.save();assert.equal(verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash).status,'completed');
 fs.appendFileSync(r.inventoryFile,' ');assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash),e=>e.verificationDiagnostic.stage==='inventory-receipt-invalid');
 const forged=structuredClone(r.inventory);forged.entries[0][4]='0'.repeat(64);fs.writeFileSync(r.inventoryFile,JSON.stringify(forged));r.receipt.installedInventory.sha256=digest(fs.readFileSync(r.inventoryFile));r.receipt.installedInventory.bytes=fs.statSync(r.inventoryFile).size;hash=r.save();assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash),e=>e.verificationDiagnostic.stage==='inventory-receipt-invalid');
 fs.writeFileSync(r.inventoryFile,JSON.stringify(r.inventory));r.receipt.installedInventory.sha256=digest(fs.readFileSync(r.inventoryFile));r.receipt.installedInventory.bytes=fs.statSync(r.inventoryFile).size;hash=r.save();fs.writeFileSync(path.join(r.modules,'actual-added'),'a');
 let error;try{verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash);}catch(e){error=e;}assert.equal(error.verificationDiagnostic.stage,'digest-mismatch');assert.equal(privateVerificationDiagnostic(error).changes.added[0].path,'actual-added');assert.equal(publicVerificationDiagnostic(error,r.tree).changes.addedCount,1);
 delete r.receipt.installedInventory;hash=r.save();assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash),e=>e.verificationDiagnostic.changes.status==='unavailable');
 r.receipt.installedInventory={status:'unavailable',reason:'byte-budget'};fs.unlinkSync(path.join(r.modules,'actual-added'));hash=r.save();assert.equal(verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash).status,'completed');
 r.receipt.installedInventory={status:'complete',filename:'installed-inventory.json',sha256:'a'.repeat(64),bytes:16*1024**2+1};hash=r.save();assert.throws(()=>verifyUpstreamInstallation(f.selection,f.id,f.root,r.file,hash),e=>e.verificationDiagnostic.stage==='inventory-receipt-invalid');
});
test('successful comparative fault preservation cannot qualify post-run installed drift; raw details stay separate',t=>{
 const f=fixed(t),r=inventoryReceipt(f),hash=r.save(),profile={reviewed:true,candidateId:f.id,root:f.root,scope:'Constructed controller drift control; not an upstream installation claim',config:{adapter:'node',discovery:'native'},expectedFailureNames:['a'],upstreamInstallation:{receiptPath:r.file,expectedSha256:hash}};
 const prepared=preparePublicCandidate(f.selection,f.id,profile),root=fixture(t,{}),relative='.tddswarm/pilots/installed-drift',originalWrite=fs.writeFileSync;let introduced=false;
 fs.writeFileSync=function(file,...args){const result=originalWrite.call(this,file,...args);if(String(file)===path.join(root,relative,'assessment.json')){introduced=true;originalWrite.call(this,path.join(r.modules,'cache-marker'),'observed drift');}return result;};
 let attempt;try{attempt=executePreparedPublic(root,f.selection,prepared,relative);}finally{fs.writeFileSync=originalWrite;}
 assert.equal(introduced,true);assert.equal(attempt.assessment.preservedFaultTrials,2);assert.equal(attempt.assessment.qualified,false);assert.equal(publicAttemptSummary(f.selection,[attempt]).qualified,0);
 const diagnostic=attempt.assessment.upstreamInstallationVerification;assert.equal(diagnostic.stage,'digest-mismatch');assert.equal(diagnostic.changes.addedCount,1);assert.equal(JSON.stringify(diagnostic).includes('cache-marker'),false);const raw=fs.readFileSync(path.join(root,relative,'upstream-installation-drift.json'));assert.equal(diagnostic.driftReceiptSha256,digest(raw));assert.equal(JSON.parse(raw).changes.added[0].path,'cache-marker');assert.equal(raw.includes(Buffer.from(f.root)),false);assert.equal(git(f.root,'status','--porcelain'),'');
});
