import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {assessOriginalNative,profileEnvironment,profileManifest,parseProfileArguments,phase} from '../scripts/vite-react-native-profile.js';
function directory(t){const p=fs.mkdtempSync(path.join(os.tmpdir(),'testlore-native-profile-'));t.after(()=>fs.rmSync(p,{recursive:true,force:true}));return p;}
function native(project,rows){const files=[...new Set(rows.map(r=>r.file))];return {success:true,numTotalTests:rows.length,numPassedTests:rows.filter(r=>r.status==='passed').length,numFailedTests:rows.filter(r=>r.status==='failed').length,numPendingTests:rows.filter(r=>r.status!=='passed'&&r.status!=='failed').length,numRuntimeErrorTestSuites:0,numTotalTestSuites:files.length,numPassedTestSuites:files.filter(file=>!rows.some(r=>r.file===file&&r.status==='failed')).length,numFailedTestSuites:files.filter(file=>rows.some(r=>r.file===file&&r.status==='failed')).length,numPendingTestSuites:0,numTodoTests:0,testResults:files.map(file=>({name:path.join(project,file),status:rows.some(r=>r.file===file&&r.status==='failed')?'failed':'passed',message:'',assertionResults:rows.filter(r=>r.file===file).map(r=>({fullName:r.name,status:r.status,failureMessages:r.status==='failed'?['Constructed assertion failure']:[]}))}))};}
test('exact original serve inventory preserves the two pending identities and rejects case drift',()=>{const manifest=profileManifest(),root='/tmp/pinned-project',report=native(root,manifest.serveCases);const result=assessOriginalNative(report,root,'serve');assert.equal(result.complete,true);assert.equal(result.pendingCases.length,2);report.testResults[0].assertionResults[0].fullName+=' drift';assert.equal(assessOriginalNative(report,root,'serve').complete,false);});
test('all pending build assertions cannot establish execution, even with matching counts and file scope',()=>{const manifest=profileManifest(),root='/tmp/pinned-project';const report=native(root,manifest.buildScope.files.map(file=>({file,name:'build assertion',status:'pending'})));assert.equal(assessOriginalNative(report,root,'build').complete,false);report.testResults[0].assertionResults[0].status='passed';report.numPassedTests=1;report.numPendingTests--;assert.equal(assessOriginalNative(report,root,'build').complete,true);});
test('private npm configurations are distinct; credential-bearing environment entries are excluded',t=>{const root=directory(t),env=profileEnvironment(root,{GH_TOKEN:'secret',NPM_TOKEN:'secret',NODE_OPTIONS:'--require bad',LANG:'C'});assert.notEqual(env.NPM_CONFIG_USERCONFIG,env.NPM_CONFIG_GLOBALCONFIG);assert.equal(env.GH_TOKEN,undefined);assert.equal(env.NODE_OPTIONS,undefined);assert.equal(env.LANG,'C');assert.throws(()=>parseProfileArguments(['--run']));assert.throws(()=>parseProfileArguments(['--run','--output',root,'--project','/tmp/other']));});
function context(output){const manifest=profileManifest();return {output,project:output,env:{PATH:path.dirname(process.execPath)+':/usr/bin:/bin'},manifest:{...manifest,resources:{...manifest.resources,stopFreeBytes:0,maximumWorkspaceBytes:1024**3,maximumPhaseOutputBytes:16,resourcePollMs:100}},report:{phases:[]}};}
test('a fast native zero exit cannot bypass output or final deadline checks',async t=>{const output=directory(t),c=context(output);await assert.rejects(()=>phase(c,'overflow',[process.execPath,'-e','process.stdout.write("01234567890123456789")']),/phase-output-limit/);await assert.rejects(()=>phase(c,'deadline',[process.execPath,'-e',''],1),/phase-deadline/);assert.equal(c.report.phases.length,2);assert.ok(c.report.phases.every(r=>r.status==='failed'));});
test('an observed surviving descendant rejects a successful parent and cleanup is retained',async t=>{const output=directory(t),c=context(output);c.manifest.resources.maximumPhaseOutputBytes=1024;const script='const {spawn}=require("child_process");const child=spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{stdio:"ignore",detached:true});console.log(child.pid);setTimeout(()=>process.exit(0),350)';await assert.rejects(()=>phase(c,'survivor',[process.execPath,'-e',script]),/surviving-descendants/);const record=c.report.phases[0];assert.equal(record.exitCode,0);assert.ok(record.descendantCleanup.observed>0);assert.ok(record.descendantCleanup.survivingAtClose>0);});
