import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {phase,profileManifest} from '../scripts/vite-react-native-profile.js';import {readBoundedBytes,runChallenges} from '../scripts/vite-react-profile-challenges.js';import {snapshotDerivedArtifacts,retainDerivedPreimage,restoreDerivedArtifacts,derivedMetadata} from '../scripts/vite-react-derived-artifacts.js';
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'testlore-challenge-cleanup-'))),project=path.join(root,'project'),dist=path.join(project,'packages/plugin-react/dist'),output=path.join(root,'output');fs.mkdirSync(path.join(dist,'nested'),{recursive:true});fs.mkdirSync(output);fs.writeFileSync(path.join(dist,'index.js'),'original-js',{mode:0o640});fs.writeFileSync(path.join(dist,'index.cjs'),'original-cjs',{mode:0o600});fs.writeFileSync(path.join(dist,'nested/chunk.js'),'original-chunk',{mode:0o644});t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,project,dist,output};}
function context(output,project){const manifest=profileManifest();return {output,project,env:{PATH:path.dirname(process.execPath)+':/usr/bin:/bin'},manifest:{...manifest,resources:{...manifest.resources,stopFreeBytes:0,maximumWorkspaceBytes:8*1024**2,maximumNativeReportBytes:32}},report:{phases:[]}};}
test('challenge native report paths are capped live and at fast zero-exit close',async t=>{const f=fixture(t);for(const [label,wait]of [['fast-report',false],['live-report',true]]){const c=context(f.output,f.project),native=path.join(f.output,label+'.native.json'),code='require("fs").writeFileSync(process.argv[1],"x".repeat(128));'+(wait?'setInterval(()=>{},1000)':'');await assert.rejects(()=>phase(c,label,[process.execPath,'-e',code,native],1000,{},[native]),/native-report-output-limit/);assert.equal(c.report.phases[0].reason,'native-report-output-limit');assert.ok(c.report.phases[0].elapsedMs<1500);}});
test('bounded native/seed reads reject overflow and symlink targets before allocating contents',t=>{const f=fixture(t),file=path.join(f.output,'oversized.native.json');fs.writeFileSync(file,'123456789');assert.throws(()=>readBoundedBytes(file,8),/Bounded regular/);assert.throws(()=>readBoundedBytes(file),/finite byte/);const link=path.join(f.output,'linked.native.json');fs.symlinkSync(file,link);assert.throws(()=>readBoundedBytes(link,100));assert.equal(readBoundedBytes(file,9).toString(),'123456789');});
test('an actually killed builder restores exact saved derived bytes/modes/inventory with no cleanup command',async t=>{const f=fixture(t),snapshot=snapshotDerivedArtifacts(f.project),preimage=retainDerivedPreimage(path.join(f.output,'preimage'),snapshot),outside=path.join(f.root,'outside-original');fs.writeFileSync(outside,'outside unchanged');const c=context(f.output,f.project),code='const fs=require("fs"),p=process.argv[1];fs.writeFileSync(p+"/index.js","fault");fs.rmSync(p+"/nested",{recursive:true});fs.writeFileSync(p+"/new.tmp","new");fs.symlinkSync(process.argv[2],p+"/linked");setInterval(()=>{},1000)';let killed=false;try{await phase(c,'killed-builder',[process.execPath,'-e',code,f.dist,outside],60);}catch(error){assert.match(error.message,/phase-deadline/);killed=true;assert.equal(fs.readFileSync(path.join(f.dist,'index.js'),'utf8'),'fault');}finally{const restored=restoreDerivedArtifacts(f.project,snapshot);assert.equal(restored.commandExecuted,false);assert.equal(restored.restored,true);}assert.equal(killed,true);assert.ok(c.report.phases[0].signal);assert.deepEqual(derivedMetadata(snapshotDerivedArtifacts(f.project)),preimage.metadata);assert.equal(fs.readFileSync(outside,'utf8'),'outside unchanged');assert.equal(fs.existsSync(path.join(f.dist,'linked')),false);assert.equal(fs.existsSync(path.join(f.dist,'new.tmp')),false);});
test('failed restoration keeps a dirty profile marker that prevents any later seed reuse',async t=>{const f=fixture(t),snapshot=snapshotDerivedArtifacts(f.project);snapshot.entries.find(row=>row.kind==='file').bytes[0]^=1;assert.throws(()=>restoreDerivedArtifacts(f.project,snapshot),/preimage bytes changed/);fs.writeFileSync(path.join(f.root,'.testlore-derived-artifacts-dirty.json'),'{}');await assert.rejects(()=>runChallenges({run:true,profile:f.root,cases:['source']}),/un-restored derived/);});
test('derived snapshots reject aliased roots and hardlinks instead of traversing outside the owned directory',t=>{const f=fixture(t),link=path.join(f.dist,'alias.js');fs.linkSync(path.join(f.dist,'index.js'),link);assert.throws(()=>snapshotDerivedArtifacts(f.project),/aliases/);fs.unlinkSync(link);const renamed=f.dist+'-old';fs.renameSync(f.dist,renamed);fs.symlinkSync(renamed,f.dist);assert.throws(()=>snapshotDerivedArtifacts(f.project),/real directories/);});

test('exactly 1001 flat derived entries reject the inventory bound',t=>{const f=fixture(t);fs.rmSync(f.dist,{recursive:true});fs.mkdirSync(f.dist);for(let i=0;i<1001;i++)fs.writeFileSync(path.join(f.dist,'entry-'+i),'');assert.equal(fs.readdirSync(f.dist).length,1001);assert.throws(()=>snapshotDerivedArtifacts(f.project),/inventory exceeds bound/);});
