// Dependency-free bounded transport for qualification bootstrap; imports never install tools.
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync,spawn} from 'node:child_process';
import {fileIdentity} from './worker-identity.js';

export async function boundedInstallProcess(command,args,{cwd,directory,timeoutMs=180000,reserveBytes=1024**3,maxGrowthBytes=450*1024**2,maxLogBytes=2*1024**2,env=process.env,terminateDescendants=false}={}){
 if(process.platform==='win32')throw Error('Installation process-group deadlines unsupported on Windows');
 const free=()=>{const s=fs.statfsSync(directory);return s.bavail*s.bsize;};const initial=free();if(initial<reserveBytes)throw Error('Installation disk reserve unavailable');const stdoutFile=path.join(directory,'stdout.log'),stderrFile=path.join(directory,'stderr.log'),out=fs.openSync(stdoutFile,'wx',0o600),err=fs.openSync(stderrFile,'wx',0o600);const start=performance.now();let reason=null;
 const child=spawn(command,args,{cwd,env,stdio:['ignore',out,err],detached:true});fs.closeSync(out);fs.closeSync(err);
 const descendants=new Map();let descendantObservationFailed=false,survivingDescendantsAtClose=0;
 const processRows=()=>execFileSync('ps',['-axo','pid=,ppid=,lstart=,stat='],{encoding:'utf8',timeout:1000,maxBuffer:2*1024*1024,env}).trim().split('\n').map(line=>{const fields=line.trim().split(/\s+/);if(fields.length<8)throw Error('Process observation unavailable');return{pid:Number(fields[0]),parent:Number(fields[1]),start:fields.slice(2,7).join(' '),state:fields[7]};});
 const observeDescendants=()=>{if(!terminateDescendants)return;try{const rows=processRows(),live=new Set([child.pid]);let added=true;while(added){added=false;for(const row of rows)if(live.has(row.parent)&&!live.has(row.pid)){live.add(row.pid);descendants.set(row.pid,row.start);added=true;}}}catch{descendantObservationFailed=true;}};
 const surviving=()=>{if(!terminateDescendants)return[];try{return processRows().filter(row=>descendants.get(row.pid)===row.start&&!row.state.includes('Z'));}catch{descendantObservationFailed=true;return[];}};
 const stop=why=>{reason ||= why;observeDescendants();for(const row of surviving().reverse()){try{process.kill(-row.pid,'SIGKILL');}catch{}try{process.kill(row.pid,'SIGKILL');}catch{}}try{process.kill(-child.pid,'SIGTERM');}catch{}setTimeout(()=>{try{process.kill(-child.pid,'SIGKILL');}catch{}},250).unref();};
 const observe=()=>{const available=free(),stdoutBytes=fs.statSync(stdoutFile).size,stderrBytes=fs.statSync(stderrFile).size,durationMs=performance.now()-start;const observedReason=durationMs>timeoutMs?'timeout':available<reserveBytes?'disk-reserve':initial-available>maxGrowthBytes?'disk-growth':stdoutBytes+stderrBytes>maxLogBytes?'log-budget':null;return{availableBytes:available,growthBytes:initial-available,stdoutBytes,stderrBytes,durationMs,reason:observedReason};};
 const timer=setInterval(()=>{try{observeDescendants();const state=observe();if(state.reason)stop(state.reason);}catch{stop('observation-failed');}},100);
 return await new Promise(resolve=>{child.once('error',error=>{clearInterval(timer);resolve({exitCode:null,signal:null,reason:'spawn-failed',error:error.code,durationMs:Math.round(performance.now()-start)});});child.once('close',(exitCode,signal)=>{clearInterval(timer);let state;try{state=observe();if(state.reason)stop(state.reason);}catch{stop('observation-failed');}if(terminateDescendants){survivingDescendantsAtClose=surviving().length;if(survivingDescendantsAtClose)stop('surviving-descendants');if(descendantObservationFailed)stop('descendant-observation-failed');}const logHash=(file)=>{try{const bytes=fs.statSync(file).size;if(!state||state.stdoutBytes+state.stderrBytes>maxLogBytes||bytes>4*1024*1024)return null;return fileIdentity(file,4*1024*1024).sha256;}catch{return null;}};resolve({exitCode,signal,reason,durationMs:Math.round(performance.now()-start),finalResources:state?{availableBytes:state.availableBytes,growthBytes:state.growthBytes,stdoutBytes:state.stdoutBytes,stderrBytes:state.stderrBytes}:null,stdoutSha256:logHash(stdoutFile),stderrSha256:logHash(stderrFile),...(terminateDescendants?{descendantCleanup:{scope:'Observed process-tree/start identity best effort; unobserved/reparented children and arbitrary subprocesses are not contained',observed:descendants.size,survivingAtClose:survivingDescendantsAtClose,observationFailed:descendantObservationFailed,requested:!!reason}}:{})});});});
}
