import fs from 'node:fs';
import path from 'node:path';
import {safePath,readConfig} from './files.js';

// Add the ongoing quality layer to the improvement branch. Existing policy is preserved.
export function installQualityLayer(root, options = {}) {
  const written=[];
  const reference=options.actionRef||'main';const defaultBranch=options.defaultBranch||'main';
  if(!/^[A-Za-z0-9._/-]+$/.test(reference)||reference.includes('..'))throw new Error('Invalid action reference');
  if(!/^[A-Za-z0-9._/-]+$/.test(defaultBranch)||defaultBranch.includes('..'))throw new Error('Invalid default branch');
  const configPath=safePath(root,'tddswarm.config.json');
  if(!fs.existsSync(configPath)){
    let pkg={};try{pkg=JSON.parse(fs.readFileSync(safePath(root,'package.json'),'utf8'));}catch{}
    const deps={...pkg.dependencies,...pkg.devDependencies};
    const adapter=deps.vitest?'vitest':deps.jest?'jest':'node';
    const runner=adapter==='vitest'?['npx','--no-install','vitest','run','{files}']:adapter==='jest'?['npx','--no-install','jest','--runTestsByPath','{files}']:['node','--test','{files}'];
    fs.writeFileSync(configPath,JSON.stringify({adapter,discovery:'native',runner,alwaysRun:[],dependencies:{},ignoreChanges:[],fullRunEvery:20},null,2)+'\n');written.push('tddswarm.config.json');
  }
  const ignorePath=safePath(root,'.gitignore');const ignore=fs.existsSync(ignorePath)?fs.readFileSync(ignorePath,'utf8'):'';
  if(!ignore.split(/\r?\n/).some(s=>['.tddswarm/','.tddswarm','/.tddswarm/'].includes(s.trim()))){fs.writeFileSync(ignorePath,ignore+(ignore&&!ignore.endsWith('\n')?'\n':'')+'.tddswarm/\n');written.push('.gitignore');}
  if(options.ci===false)return written;
  const workflow='.github/workflows/tddswarm.yml';const target=safePath(root,workflow);
  if(fs.existsSync(target))return written;
  const config=readConfig(root);
  const dependencies=fs.existsSync(safePath(root,'package-lock.json'))?'      - run: npm ci --ignore-scripts\n':fs.existsSync(safePath(root,'pnpm-lock.yaml'))?'      - run: corepack enable && pnpm install --frozen-lockfile --ignore-scripts\n':fs.existsSync(safePath(root,'yarn.lock'))?'      - run: corepack enable && yarn install --immutable\n':fs.existsSync(safePath(root,'package.json'))?'      - run: npm install --ignore-scripts\n':'';
  const external=config.integration?'      # Configure your native Python/Nx/Bazel dependencies here before the action.\n':'';
  const text=`# Generated by TDDSwarm on an improvement branch. Pin the action ref after review.
name: TDDSwarm quality engineer
on:
  pull_request:
  push:
    branches: [${defaultBranch}]
permissions:
  contents: read
concurrency:
  group: tddswarm-quality-\${{ github.ref }}
  cancel-in-progress: true
jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
${dependencies}${external}      - name: Assess quality and execute tests for the change
        uses: rudycelekli/tddswarm@${reference}
        with:
          base: \${{ github.event.pull_request.base.sha || github.event.before || github.sha }}
          mode: \${{ github.event_name == 'pull_request' && 'affected' || 'full' }}
          environment: node22-linux
          audit: 'true'
`;
  fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text);written.push(workflow);
  return written;
}
